# Generated by Django 3.2.5 on 2021-08-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='category',
        ),
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.ManyToManyField(to='polls.Category'),
        ),
    ]
