# Generated by Django 3.2.5 on 2021-08-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210806_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.category')),
                ('expenses_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.expenses')),
            ],
        ),
    ]
