# Generated by Django 3.2.5 on 2021-08-07 10:32

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_expensescategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensescategory',
            name='category_id',
            field=models.CharField(max_length=50, verbose_name=polls.models.Category),
        ),
    ]
