# Generated by Django 3.2.5 on 2021-08-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
